### ISSUE TITLE
Failed to connect to 0.0.0.0 port 1338: Connection refused

### ISSUE THREAD

**Issue by vietan32** [All-less/continuum#1]
I ran these commands on my Ubuntu 16.04: 
```
git clone https://github.com/All-less/continuum.git
cd continuum 
docker swarm init
docker stack deploy -c docker/docker-compose-frontend.yml continuum-frontend
```

And then:
```
curl -X POST --header "Content-Type:application/json" -d '{"name":"test-app", "input_type":"doubles", "default_output":"-1.0", "latency_slo_micros":100000 }' http://0.0.0.0:1338/admin/add_app
```

But I obtained:
`curl: (7) Failed to connect to 0.0.0.0 port 1338: Connection refused`

Can you explain for me? thanks in advance.

**Comment by All-less** [comment]
Hi @nguyenvietan , the connection failure is due to the out-dated docker image. I have updated it and tested it on Ubuntu. Everything should work as expected now, so could you have a retry?

**Comment by vietan32** [comment]
Hi @All-less  Thank you for your important updates.  
Now I can run the docker images as expected. But the example only sends one data sample to the Frontend. So how can I generate a stream of data to feed to the Frontend as your experiments in the paper? 
By the way, could you please update your latest version of the source code? Thanks.

**Comment by All-less** [comment]
As for data generation, you should first obtain a dataset which contains timestamps. Then you can just write a bash script that repeatedly sends the data according to the timestamp. Specifically, if you want to send a batch of data, the data in the request can be augmented into an array of vectors.
```
curl -X POST \
        --header "Content-Type:application/json" \
        -d '{"data":[[1.0, 2.0], [3.0, 4.0], [5.0, 6.0], ...]}'\
        http://0.0.0.0:1339/test-app/upload
```

And sadly, the current source code is already the latest version because of limited manpower :(

**Comment by vietan32** [comment]
Oh I got it.
I really appreciate your work on Continuum and I hope to learn more from
it.
Thank you so much for your responses.
